import { StyleSheet } from "@react-pdf/renderer";
import type { PlanOrigen } from "../lib/types";

export const ORIGIN_HEX: Record<PlanOrigen, string> = {
  PLAN: "#2563eb",
  TICKET: "#7c3aed",
  GERENCIA: "#d97706",
  USUARIO: "#0d9488",
  REQUERIMIENTO: "#059669",
  ADICIONAL: "#dc2626",
};

export const COL = {
  title: "44%",
  pct: "10%",
  trim: "8%",
  owner: "18%",
  origin: "20%",
};

export const pdf_styles = StyleSheet.create({
  page: {
    paddingTop: 52,
    paddingBottom: 36,
    paddingHorizontal: 28,
    fontFamily: "Helvetica",
    fontSize: 9,
    color: "#1e293b",
    backgroundColor: "#ffffff",
  },
  topbar: {
    position: "absolute",
    top: 16,
    left: 28,
    right: 28,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingBottom: 8,
    borderBottomWidth: 1.5,
    borderBottomColor: "#ddd6fe",
  },
  brand: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    color: "#6d28d9",
    letterSpacing: 1.2,
  },
  brandSub: { fontSize: 8, color: "#64748b", marginTop: 2 },
  year: { fontSize: 9, color: "#64748b" },
  kpiRow: { flexDirection: "row", marginBottom: 16, marginTop: 4 },
  kpiCard: {
    flex: 1,
    marginRight: 6,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 8,
    backgroundColor: "#ffffff",
  },
  kpiCardAccent: {
    flex: 1,
    marginRight: 0,
    borderWidth: 1,
    borderColor: "#7c3aed",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 8,
    backgroundColor: "#7c3aed",
  },
  kpiLabel: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#64748b",
    marginBottom: 4,
  },
  kpiLabelOnAccent: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#ede9fe",
    marginBottom: 4,
  },
  kpiValue: { fontSize: 16, fontFamily: "Helvetica-Bold", color: "#0f172a" },
  kpiValueOnAccent: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: "#ffffff",
  },
  kpiValueRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  kpiSideLines: {
    marginLeft: 6,
    flexGrow: 1,
    flexShrink: 1,
  },
  kpiMuted: { fontSize: 10, color: "#94a3b8", fontFamily: "Helvetica" },
  kpiHint: {
    fontSize: 7,
    color: "#64748b",
    fontFamily: "Helvetica",
    lineHeight: 1.2,
  },
  kpiHintOnAccent: {
    fontSize: 7,
    color: "#ede9fe",
    fontFamily: "Helvetica",
    lineHeight: 1.2,
  },
  kpiNote: {
    fontSize: 8,
    color: "#64748b",
    lineHeight: 1.35,
  },
  alcanceBox: {
    marginBottom: 14,
  },
  alcanceQuestion: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#334155",
    marginBottom: 4,
  },
  barTrack: {
    height: 5,
    borderRadius: 3,
    backgroundColor: "#e2e8f0",
    marginTop: 8,
  },
  barTrackOnAccent: {
    height: 5,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.35)",
    marginTop: 8,
  },
  barFillOnAccent: { height: 5, borderRadius: 3, backgroundColor: "#ffffff" },
  barFill: { height: 5, borderRadius: 3, backgroundColor: "#7c3aed" },
  appHead: {
    marginTop: 10,
    marginBottom: 4,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#c4b5fd",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  appName: { fontSize: 13, fontFamily: "Helvetica-Bold", color: "#4c1d95" },
  appMeta: { fontSize: 8, color: "#6d28d9" },
  moduleBlock: {
    marginLeft: 10,
    marginBottom: 8,
    paddingLeft: 8,
    borderLeftWidth: 2,
    borderLeftColor: "#ddd6fe",
  },
  moduleHead: {
    paddingVertical: 5,
    paddingHorizontal: 8,
    marginBottom: 4,
    backgroundColor: "#f5f3ff",
    borderRadius: 4,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modulePath: { fontSize: 7, color: "#7c3aed", marginBottom: 1 },
  moduleName: { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#1e293b" },
  modulePct: { fontSize: 9, fontFamily: "Helvetica-Bold", color: "#6d28d9" },
  empty: { fontSize: 8, color: "#94a3b8", marginLeft: 10, marginBottom: 8 },
  sectionIdle: {
    marginTop: 14,
    marginBottom: 6,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  groupTitle: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: "#64748b",
    textTransform: "uppercase",
    marginTop: 6,
    marginBottom: 2,
  },
  colHead: {
    flexDirection: "row",
    paddingVertical: 3,
    paddingHorizontal: 4,
    backgroundColor: "#f8fafc",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  colHeadText: {
    fontSize: 6,
    fontFamily: "Helvetica-Bold",
    color: "#94a3b8",
    textTransform: "uppercase",
  },
  taskRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 4,
    paddingHorizontal: 4,
    borderBottomWidth: 0.4,
    borderBottomColor: "#f1f5f9",
  },
  taskTitle: {
    width: COL.title,
    fontSize: 8,
    color: "#1e293b",
    paddingRight: 4,
    lineHeight: 1.3,
  },
  cellPct: {
    width: COL.pct,
    fontSize: 7,
    color: "#64748b",
    textAlign: "right",
    paddingRight: 4,
  },
  cellTrim: {
    width: COL.trim,
    fontSize: 7,
    color: "#64748b",
    textAlign: "center",
  },
  cellOwner: {
    width: COL.owner,
    fontSize: 7,
    color: "#334155",
    paddingLeft: 4,
  },
  cellOrigin: { width: COL.origin, paddingLeft: 4 },
  badge: {
    borderRadius: 7,
    paddingHorizontal: 5,
    paddingVertical: 1,
    alignSelf: "flex-start",
  },
  badgeText: { color: "#ffffff", fontSize: 6, fontFamily: "Helvetica-Bold" },
  footer: {
    position: "absolute",
    bottom: 14,
    left: 28,
    right: 28,
    fontSize: 7,
    color: "#94a3b8",
    textAlign: "center",
  },
});
